package project.model;
// Generated 11-feb-2021 17:52:46 by Hibernate Tools 4.3.1

import java.util.Set;




/**
 * Planeta generated by hbm2java
 */
public class Planeta  implements java.io.Serializable {


     private Integer idPlaneta;
     private String nombre;
     private Set<Satelite> satelites;

    public Planeta() {
    }

    public Planeta(String nombre) {
       this.nombre = nombre;
    }

    public Planeta(String nombre, Set<Satelite> satelites) {
        this.nombre = nombre;
        this.satelites = satelites;
    }
    
    
   
    public Integer getIdPlaneta() {
        return this.idPlaneta;
    }
    
    public void setIdPlaneta(Integer idPlaneta) {
        this.idPlaneta = idPlaneta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set<Satelite> getSatelites() {
        return satelites;
    }

    public void setSatelites(Set<Satelite> satelites) {
        this.satelites = satelites;
    }

    


}


