package project.model;
// Generated 11-feb-2021 17:52:46 by Hibernate Tools 4.3.1



/**
 * Satelite generated by hbm2java
 */
public class Satelite  implements java.io.Serializable {


     private Integer idSatelite;
     private String periodo;
     private String peso;
     private String medida;
     private Planeta planeta;

    public Satelite() {
    }

    public Satelite(String periodo, String peso, String medida) {
       this.periodo = periodo;
       this.peso = peso;
       this.medida = medida;
    }

    public Satelite(String periodo, String peso, String medida, Planeta planeta) {
        this.periodo = periodo;
        this.peso = peso;
        this.medida = medida;
        this.planeta = planeta;
    }
    
    
   
    public Integer getIdSatelite() {
        return this.idSatelite;
    }
    
    public void setIdSatelite(Integer idSatelite) {
        this.idSatelite = idSatelite;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public String getPeso() {
        return this.peso;
    }
    
    public void setPeso(String peso) {
        this.peso = peso;
    }
    public String getMedida() {
        return this.medida;
    }
    
    public void setMedida(String medida) {
        this.medida = medida;
    }

    public Planeta getPlaneta() {
        return planeta;
    }

    public void setPlaneta(Planeta planeta) {
        this.planeta = planeta;
    }

    


}


